RSA key pair now configured as file name.

diff --git a/scripts/vyatta-anyfi-optimizer-keygen b/scripts/vyatta-anyfi-optimizer-keygen
--- a/scripts/vyatta-anyfi-optimizer-keygen
+++ b/scripts/vyatta-anyfi-optimizer-keygen
@@ -1,39 +1,34 @@
 #!/bin/sh
 
-SIZE=2048
+FILE=/config/auth/optimizer-key-pair-${RANDOM}.pem
+BITS=2048
 
-if [ $# -ne 0 ]; then
-    echo "Usage: vyatta-anyfi-optimizer-keygen"
-    exit 1
-fi
+while getopts b:f:h c
+do
+  case $c in
+    b)       BITS=$OPTARG;;
 
-KEYFILE=/tmp/rsa${SIZE}keypair${RANDOM}.pem
+    f)       FILE=$OPTARG;;
 
-echo -n "Generating $SIZE bit RSA key pair..."
-# Generate RSA key pair file
-if ! openssl genrsa -out $KEYFILE $SIZE 2> /dev/null > /dev/null; then
-    echo "Failed to generate $SIZE bit RSA key pair."
+    h)       echo "Usage: vyatta-anyfi-optimizer-keygen [-b bits] [-f file]";
+             exit 0;;
+  esac
+done
+
+echo -n "Generating $BITS bit RSA key pair to file ${FILE}... "
+if [ -f $FILE ]; then
+    echo "Failed, file exists!"
     exit 2
+fi
+if ! openssl genrsa -out $FILE $BITS 2> /dev/null; then
+    echo "Failed!"
+    exit 3
 fi
 echo "Done."
 
-# Extract the Vyatta configuration parameter rsa-key-pair and the
-# corresponding optimizer_key to be configured into CPE:
-RSA_KEY_PAIR=$(grep -v '^-----' $KEYFILE | tr -d '\n')
-PUBLIC_PEM=$(openssl rsa -in $KEYFILE -pubout 2> /dev/null)
-
-# Delete RSA key pair file
-rm -f $KEYFILE
+OPTIMIZER_KEY=$(openssl rsa -in $FILE -pubout 2> /dev/null)
 
 cat << EOF
-
-=== RSA KEY PAIR ================================================
-
-[rsa-key-pair] =
-$RSA_KEY_PAIR
-
-[optimizer-key] =
-$PUBLIC_PEM
 
 === INSTRUCTIONS ================================================
 
@@ -41,15 +36,19 @@ $PUBLIC_PEM
 
    $ configure
    # edit service anyfi optimizer <instance>
-   # set breakout rsa-key-pair [rsa-key-pair]
+   # set breakout rsa-key-pair file '${FILE}'
    # ...
    # commit
    # save
    # exit
 
-2) Configure the public key portion of the RSA key pair in PEM format
-   [optimizer-key] into the WEBUI, CLI or TR-069 ACS (Anyfi.net vendor
-   extension InternetGatewayDevice.X_ANYFI_NET_Config.OptimizerKey).
+2) Configure your CPE with the public optimizer key below, using
+   its WEBUI, CLI or TR-069 interface (vendor extension
+   InternetGatewayDevice.X_ANYFI_NET_Config.OptimizerKey).
+
+=== OPTIMIZER KEY ===============================================
+
+$OPTIMIZER_KEY
 
 EOF
 
